services:
  - type: web
    name: group9-topic-management
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    autoDeployTrigger: "off"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: "8080"
      - key: STORAGE_PROVIDER
        value: supabase
      - key: SUPABASE_BUCKET
        value: reports
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_STORAGE_KEY
        sync: false
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_CA_CERT_FILE
        value: /etc/secrets/aiven-ca.pem
      - key: DEMO_PASSWORD
        sync: false
      - key: APP_BASE_URL
        sync: false
      - key: SERVER_SERVLET_SESSION_COOKIE_SECURE
        value: "true"
      - key: JAVA_TOOL_OPTIONS
        value: "-Xms64m -Xmx256m -XX:ReservedCodeCacheSize=64m -XX:MaxDirectMemorySize=32m -Xss512k -XX:+ExitOnOutOfMemoryError"
      - key: MAIL_ENABLED
        value: "false"
      - key: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
        value: "5"
